# Generated by Django 4.0.6 on 2022-07-20 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantidade que foi pedida')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor do pedido')),
                ('delivery_place', models.TextField(blank=True, verbose_name='Local de entrega')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='products.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-quantity'],
            },
        ),
    ]
