# Generated by Django 4.0.6 on 2022-07-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='valor do pedido'),
        ),
    ]
