# Generated by Django 4.0.6 on 2022-07-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0002_alter_solicitation_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_all', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Fatura total')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Lucro')),
            ],
        ),
    ]
