# Generated by Django 4.0.6 on 2022-07-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('price_in_sale', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='preço')),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='preço normal/de fabrica')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['price_in_sale'],
            },
        ),
    ]
